langchain4j.open-ai.chat-model.enabled=true
api-key=demo
model-name=gpt-4o-mini

langchain4j.rag.embedding-store-content-retriever.enabled=true
embedding-model=discover:auto
embedding-store=discover:auto
max-results=3
min-score=0.6
